### ISSUE TITLE
NPM does not start on Ubuntu 18.04

### ISSUE THREAD

**Issue by Apollon77** [ej52/proxmox-scripts#42]
**Script**
nginx-proxy-manager

**Describe the bug**
```
Aug  8 18:37:33 nginx-proxy-manager node[7283]: [8/8/2021] [6:37:33 PM] [Global   ] <E2><80><BA> <E2><84><B9>  info      Backend PID 7283 listening on port 3000 ...
Aug  8 18:37:33 nginx-proxy-manager node[7283]: [8/8/2021] [6:37:33 PM] [SSL      ] <E2><80><BA> <E2><9C><96>  error     Error: Command failed: certbot renew --non-interactive --quiet --config "/etc/letsencrypt.ini" --preferred-challenges "dns,http" --disable-hook-validation
Aug  8 18:37:33 nginx-proxy-manager node[7283]: Traceback (most recent call last):
Aug  8 18:37:33 nginx-proxy-manager node[7283]:   File "/usr/local/bin/certbot", line 7, in <module>
Aug  8 18:37:33 nginx-proxy-manager node[7283]:     from certbot.main import main
Aug  8 18:37:33 nginx-proxy-manager node[7283]: ModuleNotFoundError: No module named 'certbot'
Aug  8 18:37:33 nginx-proxy-manager node[7283]:     at ChildProcess.exithandler (child_process.js:390:12)
Aug  8 18:37:33 nginx-proxy-manager node[7283]:     at ChildProcess.emit (events.js:400:28)
Aug  8 18:37:33 nginx-proxy-manager node[7283]:     at maybeClose (internal/child_process.js:1055:16)
Aug  8 18:37:33 nginx-proxy-manager node[7283]:     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

```

**System info:**
 - Proxmox Version: 6.4-13
 - Ubuntu 18.04

**Comment by Apollon77** [comment]
PS: another try to execute setup ends with 

```
Collecting cffi
  Downloading https://files.pythonhosted.org/packages/f2/cd/3f5f059fed635d71047fa9ce507635088f982ab280fc24cde91d9afb9c1c/cffi-1.14.6-cp36-cp36m-manylinux1_x86_64.whl (401kB)
    100% |################################| 409kB 10.9MB/s 
Collecting certbot
  Downloading https://files.pythonhosted.org/packages/de/02/033fc8dacb3ee0ce8165aaf8427dc677cf00f4c567ca177418b9824dbf24/certbot-1.18.0-py2.py3-none-any.whl (258kB)
    100% |################################| 266kB 110.1MB/s 
Collecting pycparser (from cffi)
  Downloading https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl (112kB)
    100% |################################| 112kB 24.0MB/s 
Collecting pytz (from certbot)
  Downloading https://files.pythonhosted.org/packages/70/94/784178ca5dd892a98f113cdd923372024dc04b8d40abe77ca76b5fb90ca6/pytz-2021.1-py2.py3-none-any.whl (510kB)
    100% |################################| 512kB 63.9MB/s 
Collecting configobj>=5.0.6 (from certbot)
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-idldhma9/configobj/

```
